name: Hello

# run on an automatic trigger whenever change is pushed to branch[deployment]
on:
  push:
    branches: [main]
    
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello to users
        run: echo "Hello dosto"

      - name: say hello to username
        run: echo "Hello $USER"

  details:
    runs-on: ubuntu-latest
    steps:
      - name: version of python, docker, etc
        run: docker --version && python --version
