name: Porfolio
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
Jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.pages-url}}
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup the Github Pages
        uses: actions/configure-pages@v4
      - name: Upload static files
        uses: actions/upload-artifact@v4
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
